[project]
name = "neural-networks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "swayamshuswain", email = "swayamshu.swain@docusign.com" }
]
requires-python = ">=3.12"
dependencies = [
    "graphviz>=0.21",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
]

[tool.uv]
package = false
